function yields = import_yields(filename, dataLines)
%IMPORTFILE Import data from a text file
%  YIELDS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  YIELDS = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  yields = importfile("/Users/martijnriemers/Documents/GitHub/bachelorscriptie/data/yields.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Jun-2020 14:25:46

%% Input handling

% If filename is not specified, define defaults
if nargin < 1
    filename = "../data/yields.csv";
end

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["date", "y1", "y2", "y3", "y4", "y5", "y6", "y7", "y8", "y9", "y10"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "date", "InputFormat", "yyyy-MM");

% Import the data
yields = table2timetable(readtable(filename, opts));

end