name: Build LaTeX document

on:
  push:
    paths:
    - 'latex/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: latex
      - name: Upload LaTeX document
        uses: actions/upload-artifact@v2
        with:
          path: latex/main.pdf
